package security

type ruleSpec struct {
	id               string
	title            string
	service          string
	severity         Severity
	controlRef       string
	guidanceURL      string
	requiredServices []string
	eval             func(ctx *evalContext, r ruleSpec) (*Finding, bool)
}

func rules() []ruleSpec {
	return []ruleSpec{
		{
			id:               "CT-001",
			title:            "No logging CloudTrail trail found",
			service:          "cloudtrail",
			severity:         SeverityCritical,
			controlRef:       "CloudTrail controls (CloudTrail.1)",
			guidanceURL:      "https://docs.aws.amazon.com/securityhub/latest/userguide/cloudtrail-controls.html",
			requiredServices: []string{"cloudtrail"},
			eval:             evalCTNoLoggingTrail,
		},
		{
			id:               "CT-002",
			title:            "No multi-region CloudTrail trail found",
			service:          "cloudtrail",
			severity:         SeverityHigh,
			controlRef:       "CloudTrail controls (CloudTrail.2)",
			guidanceURL:      "https://docs.aws.amazon.com/securityhub/latest/userguide/cloudtrail-controls.html",
			requiredServices: []string{"cloudtrail"},
			eval:             evalCTNoMultiRegionTrail,
		},
		{
			id:               "CT-003",
			title:            "No CloudTrail trail with log file validation enabled",
			service:          "cloudtrail",
			severity:         SeverityMedium,
			controlRef:       "CloudTrail controls (CloudTrail.3)",
			guidanceURL:      "https://docs.aws.amazon.com/securityhub/latest/userguide/cloudtrail-controls.html",
			requiredServices: []string{"cloudtrail"},
			eval:             evalCTNoLogValidation,
		},
		{
			id:               "CFG-001",
			title:            "AWS Config recorder not active in selected regions",
			service:          "config",
			severity:         SeverityHigh,
			controlRef:       "Config controls (Config.1)",
			guidanceURL:      "https://docs.aws.amazon.com/securityhub/latest/userguide/config-controls.html",
			requiredServices: []string{"config"},
			eval:             evalConfigRecorderCoverage,
		},
		{
			id:               "GD-001",
			title:            "GuardDuty detector not enabled in selected regions",
			service:          "guardduty",
			severity:         SeverityHigh,
			controlRef:       "GuardDuty controls (GuardDuty.1)",
			guidanceURL:      "https://docs.aws.amazon.com/securityhub/latest/userguide/guardduty-controls.html",
			requiredServices: []string{"guardduty"},
			eval:             evalGuardDutyCoverage,
		},
		{
			id:               "SH-001",
			title:            "Security Hub not enabled in selected regions",
			service:          "securityhub",
			severity:         SeverityMedium,
			controlRef:       "Security Hub controls reference",
			guidanceURL:      "https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-controls-reference.html",
			requiredServices: []string{"securityhub"},
			eval:             evalSecurityHubCoverage,
		},
		{
			id:               "AA-001",
			title:            "IAM Access Analyzer not active in selected regions",
			service:          "accessanalyzer",
			severity:         SeverityMedium,
			controlRef:       "IAM controls (IAM.28)",
			guidanceURL:      "https://docs.aws.amazon.com/securityhub/latest/userguide/iam-controls.html",
			requiredServices: []string{"accessanalyzer"},
			eval:             evalAccessAnalyzerCoverage,
		},
		{
			id:               "S3-001",
			title:            "S3 bucket missing full Block Public Access posture",
			service:          "s3",
			severity:         SeverityHigh,
			controlRef:       "S3 controls (S3.8)",
			guidanceURL:      "https://docs.aws.amazon.com/securityhub/latest/userguide/s3-controls.html",
			requiredServices: []string{"s3"},
			eval:             evalS3PublicAccessBlock,
		},
		{
			id:               "S3-002",
			title:            "S3 bucket missing default encryption",
			service:          "s3",
			severity:         SeverityMedium,
			controlRef:       "S3 controls",
			guidanceURL:      "https://docs.aws.amazon.com/securityhub/latest/userguide/s3-controls.html",
			requiredServices: []string{"s3"},
			eval:             evalS3Encryption,
		},
		{
			id:               "RDS-001",
			title:            "RDS DB instance is publicly accessible",
			service:          "rds",
			severity:         SeverityHigh,
			controlRef:       "RDS controls (RDS.2)",
			guidanceURL:      "https://docs.aws.amazon.com/securityhub/latest/userguide/rds-controls.html",
			requiredServices: []string{"rds"},
			eval:             evalRDSPublic,
		},
		{
			id:               "RDS-002",
			title:            "RDS DB instance storage encryption disabled",
			service:          "rds",
			severity:         SeverityHigh,
			controlRef:       "RDS controls",
			guidanceURL:      "https://docs.aws.amazon.com/securityhub/latest/userguide/rds-controls.html",
			requiredServices: []string{"rds"},
			eval:             evalRDSEncryption,
		},
		{
			id:               "IAM-001",
			title:            "IAM console users without MFA",
			service:          "iam",
			severity:         SeverityHigh,
			controlRef:       "IAM best practices",
			guidanceURL:      "https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html",
			requiredServices: []string{"iam"},
			eval:             evalIAMConsoleWithoutMFA,
		},
		{
			id:               "IAM-002",
			title:            "Active IAM access keys older than threshold",
			service:          "iam",
			severity:         SeverityMedium,
			controlRef:       "IAM best practices",
			guidanceURL:      "https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html",
			requiredServices: []string{"iam"},
			eval:             evalIAMOldAccessKeys,
		},
		{
			id:               "SEC-001",
			title:            "Secrets Manager secret rotation disabled",
			service:          "secretsmanager",
			severity:         SeverityMedium,
			controlRef:       "Secrets Manager controls (SecretsManager.1)",
			guidanceURL:      "https://docs.aws.amazon.com/securityhub/latest/userguide/secretsmanager-controls.html",
			requiredServices: []string{"secretsmanager"},
			eval:             evalSecretsRotation,
		},
		{
			id:               "EKS-001",
			title:            "EKS cluster API endpoint is publicly accessible",
			service:          "eks",
			severity:         SeverityMedium,
			controlRef:       "EKS controls (EKS.1)",
			guidanceURL:      "https://docs.aws.amazon.com/securityhub/latest/userguide/eks-controls.html",
			requiredServices: []string{"eks"},
			eval:             evalEKSPublicAPI,
		},
		{
			id:               "EC2-001",
			title:            "Running EC2 instance has public IP",
			service:          "ec2",
			severity:         SeverityMedium,
			controlRef:       "Well-Architected Security Pillar",
			guidanceURL:      "https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/welcome.html",
			requiredServices: []string{"ec2"},
			eval:             evalEC2PublicIP,
		},
		{
			id:               "EC2-002",
			title:            "EC2 security group has world-open ingress",
			service:          "ec2",
			severity:         SeverityHigh, // elevated to critical when all-traffic exposure exists.
			controlRef:       "Well-Architected Security Pillar",
			guidanceURL:      "https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/welcome.html",
			requiredServices: []string{"ec2"},
			eval:             evalEC2WorldOpenIngress,
		},
	}
}
